[package]
name = "crypt"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
aes = "0.8"
cbc = "0.1"
cipher = "0.4"
sha2 = "0.10"
base64 = "0.22"
web-sys = { version = "0.3", features = ["Window", "Location"] }
console_error_panic_hook = "0.1"
